language: python
python:
  - "3.8"
  - "3.8-dev"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
# command to install dependencies
install:
  - pip install -r ./src/requirements.txt
# command to run tests
script:
  - pytest