version: 2.1
jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: josepadial/mii_cc
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: ./src/requirements.txt
          pkg-manager: pip
      - run:
          name: Running tests
          command: pytest
workflows:
  sample:
    jobs:
      - build-and-test