version: 2.1
jobs:
    build-and-test:
        docker:
            - image: josepadial/mii_cc
        steps:
            - checkout
            - run:
                name: Running tests
                command: pytest
workflows:
    sample:
        jobs:
          - build-and-test