version: 2.1
jobs:
  build-and-test:
    docker:
      - image: josepadial/mii_cc
    steps:
      - checkout
      - run:
        command: sudo apt install python3
      - python/install-packages:
          pip-dependency-file: ./src/requirements.txt
          pkg-manager: pip
      - run:
          name: Running tests
          command: pytest
workflows:
  sample:
    jobs:
      - build-and-test